### ISSUE TITLE
Unable to add Source

### ISSUE THREAD

**Issue by w1ld3r** [docintelapp/DocIntel#6]
Hello,
Using the readme installation procedure, I was trying to understand how to use RSS feed, when I came in trouble.
I'm unable to add any source (giving a title, home page, RSS Feed and checking "Scrape RSS feed).
The source detail is available at `http://host/Source/Details/source_title` but nothing at `http://hsot/Source/Index`.
I've tried to create a RSS Source Importer without any changes.
Lastly, when trying to create a scraper it's impossible to define a "SourceId".
Best

**Comment by xme** [comment]
+1, RSS imported added and enabled but how do we add RSS sources?

**Comment by shannaniggans** [comment]
Have you successfully Gone int Source > Add source and then scrolled down to add RSS feed and checked the scrape RSS feed option?

<img width="777" alt="image" src="https://user-images.githubusercontent.com/5997121/198169225-c4951822-1811-4b27-a95b-a1388189d878.png">

Depending on how frequently the polling is set to, you should then see the articles under Documents > View pending.

**Comment by ancailliau** [comment]
I wrote a preview documentation for that specific issue, you can find it at https://docs.docintel.org/docs/admin/importers/

There was also bugs in the importer and scraper code. These are now fixed and will be pushed for the next release on 17 Nov. Thanks for the report!

**Comment by w1ld3r** [comment]
Thanks for your reactivity.

**Comment by w1ld3r** [comment]
Hello, I'm still unable to retrieve RSS feed using the RSS importer and the configurer source.
An `[WARN] [DocIntel.Core.Importers.RSSSourceImporter] Source : RSSFeedSource` is returned by the importer.

**Comment by lbrossault** [comment]
Hello,

From Sources / view all, I cannot see all sources created previously ? (no error during creation of new RSS source)


Any idea ?
